### ISSUE TITLE
Vars on template

### ISSUE THREAD

**Issue by fernandofas** [chrisenytc/slush-generator#19]
Hi there,

I'm building a generator with slush-generator and I'm stuck with an issue.

I have made some prompt variables and as soon as I place the variable on my template, the values for these variable according to the user choice is not appearing on the .html file  where the variables suppose appear.

Below the code for the prompts:

`gulp.task('default', function (done) {
    var prompts = [{
        name: 'appName',
        message: 'What is the banner name?',
        default: defaults.appName
    },{
        name: 'appWidth',
        message: 'What is the banner width?',
        default: defaults.appWidth
    },{
        name: 'appHeight',
        message: 'What is the banner height?',
        default: defaults.appHeight
    }];`

On the Jade template, when I placed <%appWidth%> and when the .html file is rendered, instead of getting the value of that variable, it shows <%appWidth%>.

Could you please advise where is the error and how to proceed?

Thanks in advance.

Kind regards,

Fernando Fas

**Comment by closingin** [comment]
It's <%= %> and not <% %>
